version = 0.1
[default.deploy.parameters]
profile = "cloudtechcrafters.com"
stack_name = "kenya-law-gazettes"
resolve_s3 = true
s3_prefix = "kenya-law-gazettes"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
